-- MySQL Workbench Synchronization
-- Generated: 2023-05-27 18:59
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Esteban

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `SocketCrud` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `SocketCrud`.`mensajes` (
  `Id` INT(11) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
